config/routes.rb
Ingennia::Application.routes.draw do

  scope "(:locale)", locale: /es|en/ do

   root 'static#home'

   get 'home' => 'static#home'
   get 'services' => 'static#services'
   get 'rigging' => 'static#rigging'
   get 'projects' => 'static#projects'

   get 'contact' => 'contact#new'
   post 'contact' => 'contact#create'

 end

end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale
 
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
  
  def default_url_options(options={})
    logger.debug "default_url_options is passed options: #{options.inspect}\n"
    { locale: I18n.locale }
  end

end

app/controllers/cabin_controller.rb
class CabinController < ApplicationController

	def show
		@id = params[:id]
	end

	def index

	end

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    
    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      render :success
    else
      render :error
    end
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
	def home

	end

	def about
		
	end

	def services
		
	end

	def rigging
		
	end

	def projects
		
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cabin_helper.rb
module CabinHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/contact/error.html.erb
<div data-alert class='alert-box warning'> 
	Ha ocurrido un error. Por favor complete todos los campos.
	<a href="/contact" class="close">&times;</a>
</div>

app/views/contact/new.html.erb
<%
meta :title => "RiggingSteel: " + t(:contact_header),
     :description => t(:contact_text),
     :keywords => t(:keywords).gsub(/\s+/m, ' ').strip.split(" ")
%>
  <!-- Main Page Content and Sidebar -->
 
  <div class="row">
 
    <!-- Contact Details -->
    <div class="large-7 columns">
      <h3><%= t(:contact_header)%></h3>
      <p><%= t(:contact_text)%></p>

      <div class="section-container tabs" data-section>
        <section class="section">

          <div class="content" data-slug="panel1">

            <%= form_for @message, :url => contact_path do |form| %>

              <div class="row collapse">
                <div class="large-2 columns">
                  <%= form.label t(:contact_field_name), :class => "inline" %>
                </div>
                <div class="large-10 columns">
                  <%= form.text_field :name, :placeholder => t(:contact_placeholder_name) %>
                </div>
              </div>
              
              <div class="row collapse">
                <div class="large-2 columns">
                  <%= form.label t(:contact_field_email), :class => "inline" %>
                </div>
                <div class="large-10 columns">
                  <%= form.text_field :email, :placeholder => t(:contact_placeholder_email) %>
                </div>
              </div>

              <div class="row collapse">
                <div class="large-2 columns">
                  <%= form.label t(:contact_field_subject), :class => "inline" %>
                </div>
                <div class="large-10 columns">
                  <%= form.text_field :subject, :placeholder => t(:contact_placeholder_subject) %>
                </div>
              </div>
              
              <div class="field">
                <%= form.label t(:contact_field_body) %>
                <%= form.text_area :body, :placeholder => t(:contact_placeholder_body) %>
              </div>
            
              <%= form.submit t(:contact_form_button), :class => "radius button" %>

          <% end %>

          </div>
        </section>
      </div>
    </div>
 
    <!-- End Contact Details -->


    <!-- Sidebar -->
 
 
    <div class="large-5 columns">
      <br>
      <div class="panel">
        <h5><%=t(:contact_location_title)%></h5>
        <!-- Clicking this placeholder fires the mapModal Reveal modal -->
      <div class="flex-video">
      <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3329.950736101444!2d-70.6176668!3d-33.424528699999996!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9662cf63d8e993d5%3A0xc4a5d39a36f970af!2sPadre+Mariano+391%2C+Providencia%2C+Regi%C3%B3n+Metropolitana!5e0!3m2!1ses-419!2scl!4v1417534991555" width="400" height="300" frameborder="0" style="border:0"></iframe>
      </div>
        <p>
          Padre Mariano 391, Of. 704 <br/>
          Providencia.<br/>
          (Metro Pedro de Valdivia)<br/><br/>
          +56 9 84068218<br/>
          +56 2 26314141<br/>
        <%=mail_to "contacto@riggingsteel.cl", "contacto@riggingsteel.cl", subject: "[RigginSteel]"%></p>
      </div>
    </div>


    <!-- End Sidebar -->
  </div>

 
  <!-- End Main Content and Sidebar -->
 
  </body>
</html>

app/views/contact/success.html.erb
<div data-alert class="alert-box success"> 
	Gracias por su mensaje, pronto nos comunicaremos con usted.
	<a href="/home" class="close">&times;</a>
</div>

app/views/layouts/_footer.html.erb
  
  <footer class="row">
    <div class="large-12 columns">
      <hr />
      <div class="row">
        <div class="large-4 columns">
          <img src="/images/logo_50.png"/>
          <p> </p>
        </div>
        <div class="large-8 columns">
          <ul class="inline-list right">
            <li><%=  link_to t(:home), home_path%></li>
            <li><%=  link_to t(:rigging), rigging_path%></li>
            <!-- <li><%#=  link_to t(:services), services_path%></li> -->
<!--             <li><%#=  link_to t(:about_us), about_path%></li>
 --><!--            <li><%#=  link_to t(:projects), projects_path%></li> -->
            <li><%=  link_to t(:corporate_mail), "http://mail.riggingsteel.cl"%></li>
            <li><%=  link_to t(:contact_us), contact_path%></li>
          </ul>
        </div>
      </div>
    </div> 
  </footer>

app/views/layouts/_navigation.html.erb
<div class="fixed">
  <nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%=  link_to image_tag('/images/logo_bn.png'), home_path%></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="/home">Menu</a></li>
  </ul>

    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="left">
        <li><%=  link_to t(:home), home_path%></li>
        <li><%=  link_to t(:rigging), rigging_path%></li>
        <!-- <li><%#=  link_to t(:services), services_path%></li> -->
<!--         <li><%#=  link_to t(:about_us), about_path%></li>
 -->   <!--            <li><%#=  link_to t(:projects), projects_path%></li> -->

      </ul>

      <!-- Left Nav Section -->
      <ul class="right">
        <li> <%=  
              if I18n.locale == :es
                      link_to("English", url_for(:locale => :en))
              else
                      link_to("Español", url_for(:locale => :es))
              end
              %>
        </li>
        <li><%=  link_to t(:contact_us), contact_path%></li>
      </ul>
    </section>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="no-js" lang="en" data-useragent="Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Trident/6.0)">
  <head>
    <meta charset="utf-8" />
    <%= favicon_link_tag 'favicon.ico' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= metamagic %>
    <title><%= content_for?(:title) ? yield(:title) : "Rigging Steel" %></title>

    <%= stylesheet_link_tag    "application"%>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>
    
 
  <body>

    <%= render "layouts/navigation" %>

<!-- End Header and Nav -->

    <%= yield %>
    <%= render "layouts/footer" %>
    <%= javascript_include_tag "application"%>
    <script>
      $(document).foundation({topbar : {custom_back_text: false }}); 

      //analytics
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-57794521-1', 'auto');
      ga('send', 'pageview');

    </script>